Se carga el repositrio y llamos a la funcion de crear el target (que llama la funcion del target del repostirio)

In [3]:
!git clone -b silva/dia2-io https://github.com/gabriela708/ML-Household-Socioeconomic-Status.git
%cd ML-Household-Socioeconomic-Status
!pip install -q -e .
!python scripts/make_target.py

Cloning into 'ML-Household-Socioeconomic-Status'...
remote: Enumerating objects: 259, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 259 (delta 69), reused 61 (delta 54), pack-reused 168 (from 1)
Receiving objects: 100% (259/259), 8.85 MiB | 18.30 MiB/s, done.
Resolving deltas: 100% (93/93), done.
/content/ML-Household-Socioeconomic-Status
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Building editable for ses (pyproject.toml) ... done
Guardado data/processed/y_hogar.parquet  (19690 hogares)
            hogares   pct
ses
Pobre          4256  21.6
Vulnerable     4634  23.5
Media          9930  50.4
Alta            870   4.4

Podemos observar que por ejemplo, de pobre hay 4.256 hogares y esto hace parte del 21.6% de la base de datos (cruzada), tanto el GIEH y la base de datos del DANE

Varificamos que la clase pobre coincida con la del dane, por otro lado verifica que no existan valores nulos.

In [4]:
import sys; sys.path.insert(0, "src")
from ses.data.target import build_target

d = build_target(con_auditoria=True)
print(((d.ses == 0) == (d.pobre_dane == 1)).all())   # debe dar True
d.ses.value_counts().sort_index()

True

ses
0    4256
1    4634
2    9930
3     870
Name: count, dtype: int64

In [5]:
d.head()

      hogar_id  DIRECTORIO  ses           ypc            lp  pobre_dane
0  8436017_1_1     8436017    2  1.061750e+06  437134.13469           0
1  8436018_1_1     8436018    2  2.164583e+06  437134.13469           0
2  8436019_1_1     8436019    1  7.708333e+05  437134.13469           0
3  8436020_1_1     8436020    1  4.952778e+05  437134.13469           0
4  8436021_1_1     8436021    1  4.413889e+05  437134.13469           0

In [25]:
clase_porcentajes=d['ses'].value_counts()/19690
ses_porcentajes=clase_porcentajes.round(3).sort_index()*100

In [39]:
import pandas as pd

distribucion_clases = pd.DataFrame(ses_porcentajes)
distribucion_clases = pd.concat([distribucion_clases, d['ses'].value_counts()], axis=1)
distribucion_clases = distribucion_clases.reset_index()
distribucion_clases.columns = ["ses", "distribucion(%)", "conteo(cabezeras)"]
distribucion_clases

   ses  distribucion(%)  conteo(cabezeras)
0    0             21.6               4256
1    1             23.5               4634
2    2             50.4               9930
3    3              4.4                870

Se creo un data frame que contiene como se distribuyen estas categorias dentro del data set

In [40]:
distribucion_clases.to_csv("distribuciones_ses.csv", index=False)